---
- hosts: localhost 
  become: true

  tasks: 
   - name: Run update
     yum:
      update_cache: true
   - name: Install jdk
     package:
      name: java-1.8.0-openjdk
      state: present

   - name: download tomcat 
     get_url:
      url=https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.76/bin/apache-tomcat-9.0.76.tar.gz
      dest=/opt

   - name: extract tomcat
     unarchive:
      src=/opt/apache-tomcat-9.0.76.tar.gz
      dest=/opt
      remote_src=yes

     
   - name: providing execute permissions
     file:
      path: /opt/apache-tomcat-9.0.76/webapps/sample.txt
      state: file 

   - name: start tomcat service
     service: name=tomcat state=started
  

   
   - name: Deploy WAR file
     copy:
      src: /var/lib/jenkins/workspace/pipeline_job/target/addressbook.war
      dest: /var/lib/tomcat/webapps/addressbook.war
      owner: tomcat
      group: tomcat
      

   - name: Restart Tomcat service
     service:
       name: tomcat
       state: restarted
